# Generated by Django 5.2 on 2026-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
