# Generated by Django 5.2 on 2026-09-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
