# Generated by Django 5.2 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_siteconfig_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='description',
            new_name='site_description',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
