# Generated by Django 5.2 on 2026-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('mobile', 'Mobile'), ('ai', 'AI'), ('game_dev', 'Game Development'), ('language', 'Language'), ('tool', 'Tool'), ('other', 'Other')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('backend_image', models.URLField(blank=True)),
                ('frontend_image', models.URLField(blank=True)),
                ('deployment_image', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='projects.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
