# Generated by Django 5.2 on 2026-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_backend_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de données'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('mobile', 'Mobile'), ('ai', 'IA'), ('game_dev', 'Jeu vidéo'), ('language', 'Langage'), ('tool', 'Outil'), ('other', 'Autre')], max_length=20),
        ),
    ]
